### ISSUE TITLE
local variable 'seq_no' referenced before assignment

### ISSUE THREAD

**Issue by dpolz** [SkypLabs/python-hdlc-controller#1]
In hdlcontroller.py line 260 seq_no is not defined. Must be defined before try-statement in line 229. Maybe seq_no=0

**Comment by SkypLabs** [comment]
Indeed, there is a problem here. However, the sequence number to send back as an NACK must be the same as the one received in the frame which is processed. Defining it before the try-statement won't solve this issue.

After having re-read the code of [python4yahdlc](https://github.com/SkypLabs/python4yahdlc), I realised that I hadn't taken into account this case. The function [`get_data`](https://github.com/SkypLabs/python4yahdlc/blob/v1.0.4/src/python4yahdlc.c#L17) throws an [`FCSError`](https://github.com/SkypLabs/python4yahdlc/blob/v1.0.4/src/python4yahdlc.c#L60) exception without giving the sequence number to send back as an NACK. Consequently, I have to update python4yahdlc first.

Thank you for having noticed that !

**Comment by SkypLabs** [comment]
I just added a test to bring this problem to light.

Actually, when a frame with an FCS error is received, two behaviours are possible :

* Send an NACK, which implies to read the sequence number from the corrupted frame. To do so, as said above, I need to update [python4yahdlc](https://github.com/SkypLabs/python4yahdlc) first to be able to fix this issue.
* Send nothing and let the sender of the corrupted frame send it back after its timeout.

After having fixed this issue, I will add an option to choose between these two behaviours.
