### ISSUE TITLE
question: Does your controller handles SREJ frames? 

### ISSUE THREAD

**Issue by rmcavalcante** [SkypLabs/python-hdlc-controller#14]
Hello guys,

First of all, let me thank you for your work. It is nice to see initiatives like yours.
I have a situation where a series of frames are sent with segmented data in another layer.
One of these frames is rejected and a SREJ is sent back to me.
I would like to know if your controller handles SREJ and does re-transmission automatically.

BR,

Roberto

**Comment by SkypLabs** [comment]
Hi,

Thanks for your nice words!

Unfortunately no, this HDLC controller does not support SREJ frames, only the ones supported by [python4yahdlc](https://github.com/SkypLabs/python4yahdlc) which, in turns, only supports the ones of [yahdlc](https://github.com/bang-olufsen/yahdlc):

> The supported frames are limited to DATA (I-frame with Poll bit), ACK (S-frame Receive Ready with Final bit) and NACK (S-frame Reject with Final bit).

**Comment by SkypLabs** [comment]
I will close this issue. Feel free to reopen it if needed.
