### ISSUE TITLE
Example does not talk to ArduHDLC

### ISSUE THREAD

**Issue by dpolz** [SkypLabs/python-hdlc-controller#2]
What should read_uart return? Seems not to work with an bytearray like:
b'\~Tst\xbe6\~' 

Which is the output of an arduino:
```
#include <Arduhdlc.h>

#define MAX_HDLC_FRAME_LENGTH 32
 
void send_character(uint8_t data);
void hdlc_command_router(const uint8_t *framebuffer, uint16_t framelength);
 
Arduhdlc hdlc(&send_character, &hdlc_command_router, MAX_HDLC_FRAME_LENGTH);
char framebuffer[MAX_HDLC_FRAME_LENGTH];
 
void send_character(uint8_t data) {
  Serial.print((char) data);
}

void hdlc_command_router(const uint8_t *framebuffer, uint16_t framelength) {
  // Do somethin here with the data in buffer
  return;
}

void setup() {
  Serial.begin(57600);
}

void loop() {
  framebuffer[0] = 'T';
  framebuffer[1] = 's';
  framebuffer[2] = 't';
  hdlc.frameDecode(framebuffer, 3);
  delay(500);
}

/*
SerialEvent occurs whenever a new data comes in the
hardware serial RX. This routine is run between each
time loop() runs, so using delay inside loop can delay
response. Multiple bytes of data may be available.
 */
void serialEvent() {
    while (Serial.available()) {
        // get the new byte:
        char inChar = (char) Serial.read();
        hdlc.charReceiver(inChar);
    }
}
```

If lib expects string: Not every bytearray can be decoded to a string, like example above. 0xbe can't be decoded

**Comment by dpolz** [comment]
Sorry, I realized, that bridging the RX and TX on the linux system (NTC Chip cumputer) works. So sending and receiving with only your library works. I had a look at the data on the lines:

Data 'Tst' is sent by hdlcontroller as b'~\xff\tFm~'
Data 'Tst' is sent by Arduhdlc as b'~Tst\xbe6~'

So what? Are there different implementations of the HDLC? I have to find out, what you are doing to the data. Start and stop byte are matching. hdlcontroller does something to the payload and adds one byte checksum. Arduhdlc leaves the payload and seems to add two byte checksum...

**Comment by dpolz** [comment]
RTFM...

[http://www.raspiscope.com/arduino-hdlc-library/]
> What is modified from other implementations, is the used CRC16 calculation, which is changed to  _crc_ccitt_update() -function from avrlibc. This function produces the same CRC sum as the Qt CRC function qChecksum(). This makes it possible to easily implement communication between Qt GUI program in PC and Arduino, over the serial port.

Still wondering, what happens to the payload

**Comment by SkypLabs** [comment]
Hi @dpolz, and thank you for your involvement :)

I don't have the time to write a full answer right now but, in short, this Python HDLC controller is based on the Python bindings I've made ([python4yahdlc](https://github.com/SkypLabs/python4yahdlc)) of the C/C++ [yahdlc](https://github.com/bang-olufsen/yahdlc) library. Consequently, you should have a look at this last to understand what happens to the payload.

I will get back to you shortly.

**Comment by dpolz** [comment]
Hi @SkypLabs,

thanks for your answer. I had a look at the bindings. The more I think about it, the more likely it is that the arduino library is the problem.

I bridged the RX and the TX on the NTC chip again, and I can see the following data on the UART:
hdlcontroller sends "Tst" as b'\~\xff\x10Tst\x02\xf6\~'
hdlcontroller acknowledges (?) received data with b'\~\xdd!\x0c\xc0\~'
hdlcontroller sends "Tst" as b'\~\xff\x12Tstw\xcf\~'
hdlcontroller acknowledges received data with b'\~\xffA\n\xa3\~'
hdlcontroller sends "Tst" as b'\~\xff\x14Tst\xed\x84~'
hdlcontroller acknowledges received data with b'\~\xffa\x08\x82~'
...and so on

The data b'~\xff\tFm~' sent on the UART with Arduino attached was likely a ACK or NACK. Let's split the following mesage: hdlcontroller sends "Tst" as b'\~\xff\x10Tst\x02\xf6\~'

Startbyte: 0x7E ('\~' equals ASCII 0x7E)
Something: 0xFF
Upcounter: 0x10
Data: 'Tst'
CRC: 0x02F6
Stopbyte: 0x7E ('\~' equals ASCII 0x7E)

My Arduino sends "Tst" with only b'~Tst\xbe6~'

Startbyte: 0x7E ('\~' equals ASCII 0x7E)
Something: missing!
Upcounter (: missing!
Data: 'Tst'
CRC: 0xBE36 ('6' equals ASCII 0x36)
Stopbyte: 0x7E ('\~' equals ASCII 0x7E)

Am I right, that the data, which I call "upcounter", is the "sequence number"? This number seems to be contained in the ACK. But all this is not implemented in the arduino lib. I think there is much work left, to make the arduino lib real-hdlc-compliant...

**Comment by dpolz** [comment]
I configured the arduino to send the missing data by hand as a quick hack:

```
void loop() {
  framebuffer[0] = 0xFF;
  framebuffer[1] = 0x10;
  framebuffer[2] = 'T';
  framebuffer[3] = 's';
  framebuffer[4] = 't';
  hdlc.frameDecode(framebuffer, 5);
}
```

So now it should send b'~\xff\x10Tst\x02\xf6~' like hdlcontroller
But it sends '\~\xff\x10Tst\xfe\t\~'

The difference is the CRC
hldcontroller 0x02F6
Arduino: 0xFE09  ('\t' equals ASCII 0x09)

So someone misses to xor the CRC with 0xFFFF. 

[https://de.wikipedia.org/wiki/High-Level_Data_Link_Control]
> Das Frame check sequence field (Blockprüfung) besteht aus 16 Bits und enthält eine Prüfsumme der übertragenen Daten (CCITT CRC-16) dessen Binärstellen nach der Berechnung und vor der Übertragung beim Sender mit 0xFFFF xor-verknüpft werden

Which means on english that the FCS is a CCITT CRC-16, which is xored with 0xFFFF

Guess what, it's the arduino lib. I modified it:

```
void Arduhdlc::frameDecode(const char *framebuffer, uint8_t frame_length)
{
    uint8_t data;
    uint16_t fcs = CRC16_CCITT_INIT_VAL;

    this->sendchar((uint8_t)FRAME_BOUNDARY_OCTET);

    while(frame_length)
    {
        data = *framebuffer++;
        fcs = _crc_ccitt_update(fcs, data);
        if((data == CONTROL_ESCAPE_OCTET) || (data == FRAME_BOUNDARY_OCTET))
        {
            this->sendchar((uint8_t)CONTROL_ESCAPE_OCTET);
            data ^= INVERT_OCTET;
        }
        this->sendchar((uint8_t)data);
        frame_length--;
    }
	fcs ^= 0xFFFF; // HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :)
    data = low(fcs);
    if((data == CONTROL_ESCAPE_OCTET) || (data == FRAME_BOUNDARY_OCTET))
    {
        this->sendchar((uint8_t)CONTROL_ESCAPE_OCTET);
        data ^= (uint8_t)INVERT_OCTET;
    }
    this->sendchar((uint8_t)data);
    data = high(fcs);
    if((data == CONTROL_ESCAPE_OCTET) || (data == FRAME_BOUNDARY_OCTET))
    {
        this->sendchar(CONTROL_ESCAPE_OCTET);
        data ^= INVERT_OCTET;
    }
    this->sendchar(data);
    this->sendchar(FRAME_BOUNDARY_OCTET);
}
```

Unfortunatelly, I don't know, whether it has to be xored before or after the xoring with the INVERT_OCTET. I guess it's correct, because otherwise a CONTROL_ESCAPE_OCTET or FRAME_BOUNDARY_OCTET could arise on the bus.

Now I have to solve the problem with the sequence number. :(

**Comment by SkypLabs** [comment]
Don't forget that you can use the [yahdlc](https://github.com/bang-olufsen/yahdlc) library directly on Arduino. It's just a C/C++ library.

**Comment by dpolz** [comment]
Yeah, I currently try to do that. But it's not very easy for me to do. I'm rather a hardware guy. I can't use the hdlcontroller, since it uses threading and so on. So I have to write another wrapper. And I rember struggling with plain c libs in Arduino some years ago. Oh man, this will take me some time.

**Comment by dpolz** [comment]
I think this issue can be closed. Your python lib is great. Works like a charm. The problem is at arduino side. I got a copy of your c lib and included it to my arduino sketch. I had copy errno.h and errno-base.h from the web and include "  " instead of include <  > in the sketch as well as in errno.h.

I wrote a new sketch

```
#include "yahdlc.h"
#include "errno.h"

void setup() {
  // put your setup code here, to run once:
  Serial.begin(57600);
}

void loop() {
  // put your main code here, to run repeatedly:
  char str[] = "testing is fun";
  HDLCsend(str,14);
  delay(1000);
}

void HDLCsend(const char *data, uint8_t len){
  char buf[len+20];
  uint8_t buf_len;
  static uint8_t i = 0;
  i = (i + 1) % 8;
  
  yahdlc_control_t frame = {YAHDLC_FRAME_DATA, i};
  yahdlc_frame_data(&frame,data,len,buf,(unsigned int *)&buf_len);
  buf[buf_len] = 0;
  Serial.println(buf);
}
```

It outputs after reset on uart:
00
7E FF 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A (this is received correctly)
FC FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
FC FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
FC FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
FE FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
FE FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
FC FD 12 74 65 73 74 69 6E 67 20 69 73 20 66 75 6E D2 63 7E 0D 0A
the last lines are rreceived depending on data "testing is fun" works. "Huhne" not.

I don't know why it only starts with '~' after reset and then shifts the 7E to FC

I' somehow fed up with this project. I just wanted to quickly wire a temperature sensor to this shitty chip computer to build a weather server, which can be done with a raspberry pi in minutes. But the chipOS misses the 1wire kernel module, my ubuntu doesn't compile a new kernel, arduino libraries interpret a industry standard on their very own way, and bits do what they want: happy shifting. F**koff. I'll buy a thermometer :)

**Comment by SkypLabs** [comment]
Ok I close this issue.

I hope you will find a solution to your situation ! Don't hesitate to open a new issue if needed :)
