### ISSUE TITLE
serial.inWaiting() changed to serial.in_waiting

### ISSUE THREAD

**Issue by dpolz** [SkypLabs/python-hdlc-controller#3]
In newer versions of pySerial, method inWaiting() has been replaced by attribute in_waiting. See http://pyserial.readthedocs.io/en/latest/pyserial_api.html

**Comment by SkypLabs** [comment]
Thank you @dpolz :)

**Comment by itfanr** [comment]
https://pyserial.readthedocs.io/en/latest/pyserial_api.html
