### ISSUE TITLE
Raspberry pi and arduino communicate with hdlc protocol

### ISSUE THREAD

**Issue by JCStarry** [SkypLabs/python-hdlc-controller#6]
I have found an hdlc lib for arduino from @jarkko-hautakorpi. I want use this python-hdlc-controller on PC/Raspbery pi  and Arduhdlc on Arduino,  could it work together?
https://github.com/jarkko-hautakorpi/Arduhdlc

Thanks!

**Comment by SkypLabs** [comment]
Hi @JCStarry and thank you for your interest in this project.

The library made by @jarkko-hautakorpi only implements the framing and error checking mechanisms of the HDLC specification and not the sequence number, the acknowledgement frames, etc. It is consequently incompatible with this HDLC controller.

If you want to use a more complete HDLC implementation (and so compatible with this controller), I recommend you use either [yahdlc](https://github.com/bang-olufsen/yahdlc) (C) or [hdlcpp](https://github.com/bang-olufsen/hdlcpp) (C++).
